steps:
- name: gcr.io/cloud-builders/gsutil
  # we use rsync and not cp so that the step does not fail the first time it is run
  args: ['rsync', 'gs://gradle_cache_TestForBuildapk/', '.']
- name: 'gcr.io/$PROJECT_ID/android-builder'
  entrypoint: 'gradle-build'
  args: ['-g', '.gradle', 'assemble']
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'cache.zip', 'gs://gradle_cache_TestForBuildapk/cache.zip']
